import { Play } from "lucide-react";

const demos = [
  { id: 1, brand: "TechGadget Pro", style: "Reel", color: "from-blue-500/20 to-cyan-500/20" },
  { id: 2, brand: "BeautyGlow", style: "Story", color: "from-pink-500/20 to-purple-500/20" },
  { id: 3, brand: "FitLife Nutrition", style: "Ad", color: "from-green-500/20 to-emerald-500/20" },
  { id: 4, brand: "StyleWear", style: "Reel", color: "from-orange-500/20 to-amber-500/20" },
  { id: 5, brand: "HomeChef Kit", style: "Story", color: "from-red-500/20 to-rose-500/20" },
  { id: 6, brand: "PetCare Plus", style: "Ad", color: "from-violet-500/20 to-indigo-500/20" },
  { id: 7, brand: "EcoBottle", style: "Reel", color: "from-teal-500/20 to-cyan-500/20" },
  { id: 8, brand: "GameZone", style: "Story", color: "from-fuchsia-500/20 to-pink-500/20" },
];

export function DemoCarousel() {
  const duplicatedDemos = [...demos, ...demos];

  return (
    <section className="py-20 overflow-hidden">
      <div className="container mx-auto px-6 mb-12">
        <div className="text-center space-y-4">
          <h2 className="text-3xl sm:text-4xl font-bold">
            See What Others Are Creating
          </h2>
          <p className="text-muted-foreground max-w-2xl mx-auto">
            Explore UGC ads generated by brands just like yours
          </p>
        </div>
      </div>

      {/* Scrolling Carousel */}
      <div className="relative">
        {/* Gradient Masks */}
        <div className="absolute left-0 top-0 bottom-0 w-32 bg-gradient-to-r from-background to-transparent z-10" />
        <div className="absolute right-0 top-0 bottom-0 w-32 bg-gradient-to-l from-background to-transparent z-10" />

        <div className="flex animate-marquee">
          {duplicatedDemos.map((demo, index) => (
            <div
              key={`${demo.id}-${index}`}
              className="flex-shrink-0 w-72 mx-3 group"
            >
              <div className="glass rounded-2xl p-2 card-hover">
                {/* Video Thumbnail */}
                <div className={`relative aspect-[9/16] rounded-xl overflow-hidden bg-gradient-to-br ${demo.color}`}>
                  {/* Play Button */}
                  <div className="absolute inset-0 flex items-center justify-center">
                    <div className="w-14 h-14 rounded-full bg-background/80 backdrop-blur-sm flex items-center justify-center group-hover:scale-110 transition-transform duration-300">
                      <Play className="w-6 h-6 text-foreground ml-1" />
                    </div>
                  </div>

                  {/* Style Badge */}
                  <div className="absolute top-3 right-3 px-3 py-1 rounded-full bg-background/80 backdrop-blur-sm text-xs font-medium">
                    {demo.style}
                  </div>

                  {/* Brand Info */}
                  <div className="absolute bottom-0 left-0 right-0 p-4 bg-gradient-to-t from-background/90 to-transparent">
                    <p className="font-semibold text-foreground">{demo.brand}</p>
                  </div>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
 
    </section>
  );
}
