import { Play } from "lucide-react";

const demos = [
  {
    id: 1,
    brand: "SmartWatch X",
    style: "Reel",
    videoUrl: "https://res.cloudinary.com/di5ek1v7y/video/upload/v1769017535/tl6iukoalyrbbrfxbq6q.mp4",
    poster: "https://images.pexels.com/photos/267394/pexels-photo-267394.jpeg"
  },
  {
    id: 5,
    brand: "Coffee Brand",
    style: "Story",
    videoUrl: "https://res.cloudinary.com/di5ek1v7y/video/upload/v1769982780/wsltcmgzmmyaqe6clhlc.mp4",
    poster: "https://images.pexels.com/photos/33242/coffee-cup-beverage-beverage-cup.jpg"
  },
  {
    id: 2,
    brand: "GlowSkin Serum",
    style: "Story",
    videoUrl: "https://res.cloudinary.com/di5ek1v7y/video/upload/v1769117494/c4guouewxzpkzyfxshdt.mp4",
    poster: "https://images.pexels.com/photos/3762871/pexels-photo-3762871.jpeg"
  },
  {
    id: 3,
    brand: "Fitness Protein",
    style: "Ad",
    videoUrl: "https://res.cloudinary.com/di5ek1v7y/video/upload/v1769117635/kxppjs0tusczbmepnucj.mp4",
    poster: "https://images.pexels.com/photos/3757331/pexels-photo-3757331.jpeg"
  },
  {
    id: 4,
    brand: "Fashion Apparel",
    style: "Reel",
    videoUrl: "https://res.cloudinary.com/di5ek1v7y/video/upload/v1769124564/tneug2h70y6nb5xp5bh3.mp4",
    poster: "https://images.pexels.com/photos/3758112/pexels-photo-3758112.jpeg"
  },
  {
    id: 5,
    brand: "Coffee Brand",
    style: "Story",
    videoUrl: "https://res.cloudinary.com/di5ek1v7y/video/upload/v1769121384/soi6xnjuyzbx9tg52duq.mp4",
    poster: "https://images.pexels.com/photos/33242/coffee-cup-beverage-beverage-cup.jpg"
  }
  
];


export function DemoCarousel() {
  const duplicatedDemos = [...demos, ...demos];

  return (
    <section className="py-20 overflow-hidden bg-[#030303]">
      <div className="container mx-auto px-6 mb-12">
        <div className="text-center space-y-4">
          <h2 className="text-3xl sm:text-4xl font-bold text-white tracking-tight">
            See What Others Are Creating
          </h2>
          <p className="text-slate-400 max-w-2xl mx-auto">
            Explore high-converting Kreo ads generated by brands just like yours
          </p>
        </div>
      </div>

      <div className="relative">
        {/* Soft Gradient Masks */}
        <div className="absolute left-0 top-0 bottom-0 w-40 bg-gradient-to-r from-[#030303] to-transparent z-20" />
        <div className="absolute right-0 top-0 bottom-0 w-40 bg-gradient-to-l from-[#030303] to-transparent z-20" />

        <div className="flex animate-marquee hover:[animation-play-state:paused]">
          {duplicatedDemos.map((demo, index) => (
            <div
              key={`${demo.id}-${index}`}
              className="flex-shrink-0 w-72 mx-3 group"
            >
              <div className="relative aspect-[9/16] rounded-2xl overflow-hidden border border-white/10 bg-zinc-900 group-hover:border-blue-500/50 transition-all duration-500 shadow-2xl">
                
                {/* Background Video (Silent Auto-preview) */}
                <video 
                  src={demo.videoUrl}
                  poster={demo.poster}
                  autoPlay
                  loop
                  muted
                  playsInline
                  className="absolute inset-0 w-full h-full object-cover opacity-60 group-hover:opacity-100 group-hover:scale-110 transition-all duration-700"
                />

                {/* Glassy Play Button Overlay */}
                <div className="absolute inset-0 flex items-center justify-center z-10">
                  <div className="w-14 h-14 rounded-full bg-white/10 backdrop-blur-md border border-white/20 flex items-center justify-center opacity-0 group-hover:opacity-100 scale-75 group-hover:scale-100 transition-all duration-300">
                    <Play className="w-6 h-6 text-white fill-white ml-1" />
                  </div>
                </div>

                {/* Badge Overlay */}
                <div className="absolute top-4 right-4 z-10">
                  <div className="px-3 py-1 rounded-full bg-black/60 backdrop-blur-xl border border-white/10 text-[10px] font-bold text-white uppercase tracking-widest">
                    {demo.style}
                  </div>
                </div>

                {/* Bottom Info Gradient */}
                <div className="absolute bottom-0 left-0 right-0 p-5 bg-gradient-to-t from-black via-black/40 to-transparent z-10">
                  <p className="font-bold text-white group-hover:text-blue-400 transition-colors uppercase text-xs tracking-wider">
                    {demo.brand}
                  </p>
                </div>

              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}