import { Play } from "lucide-react";

const demos = [
  { 
    id: 1, 
    brand: "TechGadget Pro", 
    style: "Reel", 
    videoUrl: "https://videos.pexels.com/video-files/3201477/3201477-uhd_1440_2732_25fps.mp4", // Desk setup/Tech
    poster: "https://images.pexels.com/photos/356056/pexels-photo-356056.jpeg" 
  },
  { 
    id: 2, 
    brand: "BeautyGlow", 
    style: "Story", 
    videoUrl: "https://videos.pexels.com/video-files/3327108/3327108-uhd_1440_2732_24fps.mp4", // Skincare/Cream
    poster: "https://images.pexels.com/photos/3762871/pexels-photo-3762871.jpeg"
  },
  { 
    id: 3, 
    brand: "FitLife Nutrition", 
    style: "Ad", 
    videoUrl: "https://videos.pexels.com/video-files/3494713/3494713-uhd_1440_2732_30fps.mp4", // Fitness/Workout
    poster: "https://images.pexels.com/photos/3757331/pexels-photo-3757331.jpeg"
  },
  { 
    id: 4, 
    brand: "StyleWear", 
    style: "Reel", 
    videoUrl: "https://videos.pexels.com/video-files/3751023/3751023-uhd_1440_2732_25fps.mp4", // Fashion/Model
    poster: "https://images.pexels.com/photos/3758112/pexels-photo-3758112.jpeg"
  },
  { 
    id: 5, 
    brand: "HomeChef Kit", 
    style: "Story", 
    videoUrl: "https://videos.pexels.com/video-files/2802058/2802058-uhd_1440_2732_24fps.mp4", // Cooking/Kitchen
    poster: "https://images.pexels.com/photos/33242/coffee-cup-beverage-beverage-cup.jpg"
  },
  { 
    id: 6, 
    brand: "PetCare Plus", 
    style: "Ad", 
    videoUrl: "https://videos.pexels.com/video-files/4064363/4064363-uhd_1440_2732_25fps.mp4", // Cute Pet
    poster: "https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg"
  },
  { 
    id: 7, 
    brand: "EcoBottle", 
    style: "Reel", 
    videoUrl: "https://videos.pexels.com/video-files/4202347/4202347-uhd_1440_2732_25fps.mp4", // Product/Water
    poster: "https://images.pexels.com/photos/1188741/pexels-photo-1188741.jpeg"
  },
  { 
    id: 8, 
    brand: "GameZone", 
    style: "Story", 
    videoUrl: "https://videos.pexels.com/video-files/3163534/3163534-uhd_1440_2732_30fps.mp4", // Gaming Setup
    poster: "https://images.pexels.com/photos/129728/pexels-photo-129728.jpeg"
  },
];

export function DemoCarousel() {
  const duplicatedDemos = [...demos, ...demos];

  return (
    <section className="py-20 overflow-hidden bg-[#030303]">
      <div className="container mx-auto px-6 mb-12">
        <div className="text-center space-y-4">
          <h2 className="text-3xl sm:text-4xl font-bold text-white tracking-tight">
            See What Others Are Creating
          </h2>
          <p className="text-slate-400 max-w-2xl mx-auto">
            Explore high-converting UGC ads generated by brands just like yours
          </p>
        </div>
      </div>

      <div className="relative">
        {/* Soft Gradient Masks */}
        <div className="absolute left-0 top-0 bottom-0 w-40 bg-gradient-to-r from-[#030303] to-transparent z-20" />
        <div className="absolute right-0 top-0 bottom-0 w-40 bg-gradient-to-l from-[#030303] to-transparent z-20" />

        <div className="flex animate-marquee hover:[animation-play-state:paused]">
          {duplicatedDemos.map((demo, index) => (
            <div
              key={`${demo.id}-${index}`}
              className="flex-shrink-0 w-72 mx-3 group"
            >
              <div className="relative aspect-[9/16] rounded-2xl overflow-hidden border border-white/10 bg-zinc-900 group-hover:border-blue-500/50 transition-all duration-500 shadow-2xl">
                
                {/* Background Video (Silent Auto-preview) */}
                <video 
                  src={demo.videoUrl}
                  poster={demo.poster}
                  autoPlay
                  loop
                  muted
                  playsInline
                  className="absolute inset-0 w-full h-full object-cover opacity-60 group-hover:opacity-100 group-hover:scale-110 transition-all duration-700"
                />

                {/* Glassy Play Button Overlay */}
                <div className="absolute inset-0 flex items-center justify-center z-10">
                  <div className="w-14 h-14 rounded-full bg-white/10 backdrop-blur-md border border-white/20 flex items-center justify-center opacity-0 group-hover:opacity-100 scale-75 group-hover:scale-100 transition-all duration-300">
                    <Play className="w-6 h-6 text-white fill-white ml-1" />
                  </div>
                </div>

                {/* Badge Overlay */}
                <div className="absolute top-4 right-4 z-10">
                  <div className="px-3 py-1 rounded-full bg-black/60 backdrop-blur-xl border border-white/10 text-[10px] font-bold text-white uppercase tracking-widest">
                    {demo.style}
                  </div>
                </div>

                {/* Bottom Info Gradient */}
                <div className="absolute bottom-0 left-0 right-0 p-5 bg-gradient-to-t from-black via-black/40 to-transparent z-10">
                  <p className="font-bold text-white group-hover:text-blue-400 transition-colors uppercase text-xs tracking-wider">
                    {demo.brand}
                  </p>
                </div>

              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}